### ISSUE TITLE
This looks cool, but what about sound ?

### ISSUE THREAD

**Issue by shtefcs** [vagnervjs/frame-player#10]
Am I missing something ?

**Comment by Krato** [comment]
It looks very interesting but, Yes. What about sound??

**Comment by oryan** [comment]
You are streaming a sequence of jpegs.
Jpegs don't have sound.

You also cannot play sound on a mobile device unless you are in full screen media mode. So... yeah... there is no sound...

**Comment by shtefcs** [comment]
Aha ...

Got it, tnx :)
