### ISSUE TITLE
Video.js plugin?

### ISSUE THREAD

**Issue by heff** [vagnervjs/frame-player#2]
Very cool project. It'd be great to make a video.js plugin for this. Here's some existing examples if you'd be interested: 
 - [HTML5](https://github.com/videojs/video.js/blob/v4.2.2/src/js/media/html5.js)
 - [Flash](https://github.com/videojs/video.js/blob/v4.2.2/src/js/media/flash.js)
 - [Youtube](https://github.com/eXon/videojs-youtube)
 - [Vimeo](https://github.com/eXon/videojs-vimeo)
 - [Daily Motion](https://github.com/benjipott/video.js-dailymotion)

**Comment by vagnervjs** [comment]
I think it's best to keep Frame Player as a separate lib, and keeping the focus of development on improving the library.
Anyway, thank you for proposal and sorry for the huge delay.
